//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgrammingTasks.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.users_solutions = new HashSet<users_solutions>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<users_solutions> users_solutions { get; set; }
    }
}
